const Koa = require('koa')
const app = new Koa()
const response = require('./middlewares/response')
const restfulRouter = require('./middlewares/router')
const bodyParser = require('koa-bodyparser')
const config = require('./config')
const auth = require('./middlewares/auth')
const cors = require('koa2-cors')
const {L,D,T} = require('./libs')

app.use(L.accessLogger)
app.use(cors())
app.use(T.ctxUtils)
app.use(response)
app.use(bodyParser({jsonLimit: 100 * 1024 * 1024}))
app.use(auth)
app.use(restfulRouter.routes())
app.listen(config.port)
D('Server started on port:'+config.port)

