version: '3.4'

services:
  hstiggerserver:
    image: hstiggerserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5858:5858
