version: '3.4'

services:
  hstiggerserver:
    image: hstiggerserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6001:6001

  redis:
      image: redis
      container_name: redis
      volumes:
        - ./data:/data
        - ./logs:/logs
      command:
        # 两个写入操作 只是为了解决启动后警告 可以去掉
        /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
        && echo never > /sys/kernel/mm/transparent_hugepage/enabled
        && redis-server /usr/local/etc/redis/redis.conf"
      ports:
        - 6380:6379