version: '3.4'

services:
  hstiggerserver:
    image: hstiggerserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5858:5858
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
